package main.java.IonErm.ClassWork.errors10_01;

public class Main {

    public static void toUpperCase(String upper) {
        try {
            System.out.println(upper.toUpperCase());
        } catch (NullPointerException e) {
            System.out.println("String is null");
        }
    }

    public static void main(String[] args) {
//        toUpperCase(null);

//        try {
//            throw new MyException("Custom exception occured!");
//        } catch (MyException e) {
//            System.out.println(e.getMessage());
//        }
//
//        try {
//            int[] numbers = {1, 2, 34, 5, 6, 7};
//            System.out.println(numbers[1009]);
//        } catch (Exception e) {
//            System.out.println("The error is caught - something wrong");
//        } finally {
//            System.out.println("The Try Catch is finished");
//        }

    }
}
